runtime: python39  # Menggunakan runtime standar untuk hosting HTML statis
service: fe-196  # Nama layanan App Engine, bisa diubah sesuai kebutuhan
instance_class: F1  # Kelas instance untuk App Engine (F1 adalah kelas standar yang ringan)

handles:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)

default_expiration: "1h"  # Waktu cache default